set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_C_COMPILER   /usr/bin/clang-cl)
set(CMAKE_CXX_COMPILER /usr/bin/clang-cl)
set(CMAKE_LINKER /usr/bin/lld-link-16)
set(CMAKE_AR /usr/bin/llvm-lib)
set(CMAKE_MT /usr/bin/llvm-mt-16)
set(CMAKE_RC_COMPILER /usr/bin/llvm-rc-16)

set(CMAKE_BUILD_TYPE Release)

SET(CLANG_CL_INCLUDES "/imsvc /xwin/crt/include /imsvc /xwin/sdk/include/ucrt /imsvc /xwin/sdk/include/um /imsvc /xwin/sdk/include/shared")
SET(CMAKE_CXX_FLAGS_INIT "${CLANG_CL_INCLUDES} -Wno-everything")
SET(CMAKE_C_FLAGS_INIT   "${CLANG_CL_INCLUDES} -Wno-everything")

SET(CLANG_CL_LIBS "/libpath:/xwin/crt/lib/x86_64 /libpath:/xwin/sdk/lib/um/x86_64 /libpath:/xwin/sdk/lib/ucrt/x86_64")

SET(CMAKE_EXE_LINKER_FLAGS_INIT "${CLANG_CL_LIBS}")
SET(CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT "${CLANG_CL_LIBS}")
SET(CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT "${CLANG_CL_LIBS}")
SET(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO_INIT "${CLANG_CL_LIBS}")

SET(CMAKE_SHARED_LINKER_FLAGS_INIT "${CLANG_CL_LIBS}")
SET(CMAKE_SHARED_LINKER_FLAGS_DEBUG_INIT "${CLANG_CL_LIBS}")
SET(CMAKE_SHARED_LINKER_FLAGS_RELEASE_INIT "${CLANG_CL_LIBS}")
SET(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO_INIT "${CLANG_CL_LIBS}")

SET(CMAKE_STATIC_LINKER_FLAGS_INIT "${CLANG_CL_LIBS}")
SET(CMAKE_STATIC_LINKER_FLAGS_DEBUG_INIT "${CLANG_CL_LIBS}")
SET(CMAKE_STATIC_LINKER_FLAGS_RELEASE_INIT "${CLANG_CL_LIBS}")
SET(CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO_INIT "${CLANG_CL_LIBS}")

SET(CMAKE_MODULE_LINKER_FLAGS_INIT "${CLANG_CL_LIBS}")
SET(CMAKE_MODULE_LINKER_FLAGS_DEBUG_INIT "${CLANG_CL_LIBS}")
SET(CMAKE_MODULE_LINKER_FLAGS_RELEASE_INIT "${CLANG_CL_LIBS}")
SET(CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO_INIT "${CLANG_CL_LIBS}")


set(CMAKE_FIND_ROOT_PATH /xwin)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
